initContainer:
  enabled: true
  image:
    repository: alpine/curl
    tag: latest
  command: 
    - /bin/sh
    - -c
    - |
      # Define variables
      RELEASE_TAG="15.1.367"
      DOWNLOAD_URL="https://github.com/iterativv/NostalgiaForInfinity/archive/refs/tags/v${RELEASE_TAG}.zip"
      PYTHON_FILE_PATH="NostalgiaForInfinity-${RELEASE_TAG}/NostalgiaForInfinityX5.py"
      DESTINATION="/freqtrade/user_data/strategies/NostalgiaForInfinityX5.py"

      # Download the release zip
      echo Downloading Tag ${RELEASE_TAG}.
      curl -L -o source_code.zip "${DOWNLOAD_URL}"

      # Unzip the specific file
      echo unzipping tag ${RELEASE_TAG}.
      unzip source_code.zip -d /tmp

      # Move the file to the desired destination
      cp "/tmp/${PYTHON_FILE_PATH}" "${DESTINATION}"
      cp -R "/tmp/NostalgiaForInfinity-${RELEASE_TAG}/configs" /freqtrade/


      echo Downloaded tag ${RELEASE_TAG} successfully.

      # Clean up
      echo cleaning up ...
      rm -rf /tmp/NostalgiaForInfinity-${RELEASE_TAG}
      rm source_code.zip
    

  volumeMounts: 
  - name: strategy
    mountPath: "/freqtrade/user_data/strategies"
    readOnly: false
  - name: configs
    mountPath: "/freqtrade/configs"
    readOnly: false



image:
  repository: "freqtradeorg/freqtrade"
  tag: "stable"
  # command:
  #   - tail
  # args:
  #   - -f
  #   - /dev/null
args:
  - trade
  - --db-url
  - sqlite:////freqtrade/user_data/data/tradesv3.sqlite
  - --log-file
  - /freqtrade/user_data/data/logs/freqtrade.log
  
nameOverride: "freqtrade"

service:
  type: ClusterIP
  port: 8989

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: &host freqtrade.pouria.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: freqtrade-tls-certificate

persistence:
  enabled: true
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: freqtrade
      defaultMode: 0644
    - name: strategy
      emptyDir: {}
      defaultMode: 0644
    - name: configs
      emptyDir: {}
      defaultMode: 0644
    - name: config
      configMap:
        name: freqtrade

  volumeMounts: 
  - name: data
    mountPath: "/freqtrade/user_data/data"
    readOnly: false
  - name: strategy
    mountPath: "/freqtrade/user_data/strategies"
    readOnly: false
  - name: configs
    mountPath: "/freqtrade/configs"
    readOnly: false
  - name: config
    mountPath: "/freqtrade/user_data/config.json"
    subPath: config.json
    readOnly: false

podSecurityContext:
  fsGroup: 1000

nodeSelector:
  kubernetes.io/hostname: metal4

tolerations:
  - effect: NoSchedule
    key: freqtrade
    operator: Equal
    value: "true"

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

configMap:
  enabled: true
  data:
    config.json: |
         {
            "strategy": "NostalgiaForInfinityX5",
            "add_config_files": [
              "../configs/trading_mode-spot.json",
              "../configs/pairlist-volume-mexc-usdt.json",
              "../configs/blacklist-mexc.json",
              "../configs/exampleconfig.json"
            ]
          }