{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "general.fullname" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.secret.data.envs }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}