app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/mealie-recipes/mealie
            tag: v2.0.0
          env:
            ALLOW_SIGNUP: "false"
            PUID: 1000
            PGID: 1000
            TZ: Europe/Berlin
            MAX_WORKERS: 1
            WEB_CONCURRENCY: 1
            BASE_URL: https://mealie.pouria.sh
          # envFrom:
          #   - secret: "{{ .Release.Name }}-secret"
  service:
    main:
      ports:
        http:
          port: 9000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host mealie.pouria.sh
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: mealie-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /app/data/
              subPath: data
