app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/tandoorrecipes/recipes
            tag: 1.5.20
          env:
            TZ: Europe/Berlin
            SECRET_KEY: changeme
  service:
    main:
      ports:
        http:
          port: 8080
        static:
          port: 80
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host tandoor.pouria.sh
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8080
            - path: /static
              service:
                name: main
                port: 80
            - path: /media
              service:
                name: main
                port: 80
      tls:
        - hosts:
            - *host
          secretName: tandoor-tls-certificate

  persistence:
    config:
      enabled: false
      retain: true
      # storageClass: ""
      # accessMode: ReadWriteOnce
      # size: 1Gi
    media:
      enabled: false
      mountPath: /opt/recipes/mediafiles
      retain: true
      # storageClass: ""
      # accessMode: ReadWriteOnce
      # size: 1Gi
    static:
      enabled: true
      type: emptyDir
      mountPath: /opt/recipes/staticfiles
    django-js-reverse:
      enabled: true
      type: emptyDir
      mountPath: /opt/recipes/cookbook/static/django_js_reverse

postgresql:
  enabled: true
  auth:
    database: tandoor
    postgresPassword: changeme
  primary:
    persistence:
      enabled: true
